### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by pdinklag** [pdinklag/JSFML#14]
Support Mac OS X as a targeted system.

**Comment by mantognini** [comment]
Are you no longer seeking OS X support?

**Comment by pdinklag** [comment]
Yes, but I consider the _issue_ solved, since you thankfully volunteered to build the Mac binaries. ;)
I will try to round everything up for a 2.2 build any time soon!

**Comment by mantognini** [comment]
Alright then. Let me know when you have something stable. ;-)
