### ISSUE TITLE
"Mavenize" JSFML

### ISSUE THREAD

**Issue by pdinklag** [pdinklag/JSFML#45]
See the following forum thread for the discussion:
http://en.sfml-dev.org/forums/index.php?topic=10242.0

**Comment by kinglime** [comment]
I've started using maven and this feature would be awesome. +1

**Comment by pdinklag** [comment]
I had to use Maven for a university project and while I don't like it personally, I now see how it's useful to people and know how it works.

This should be done when JSFML is to be "released" (and I definitely have to re-define the term "release" for JSFML, but that's another issue).

Note to self:
_Guide to uploading artifacts to the Central Repository_
http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by jamierocks** [comment]
You should use Gradle, and use it's maven-publish plugin :)

**Comment by pdinklag** [comment]
Closing because I stopped development of JSML.
