### ISSUE TITLE
IntRect and FloatRect API change

### ISSUE THREAD

**Issue by pdinklag** [pdinklag/JSFML#65]
Apparently, the function `intersection` that used to calculate the intersection rectangle of two rectangles, has been replaced by `intersects` that simply returns a boolean value in case there is an intersection.

Did I miss that? In any event, this should be consistent with SFML.

**Comment by mantognini** [comment]
Actually, both functions still exists. E.g. https://github.com/LaurentGomila/SFML/blob/master/include/SFML/Graphics/Rect.hpp#L118

**Comment by pdinklag** [comment]
Ah, I'm starting to understand the issue now.

Since I decided that the rectangle classes should be immutable and thus I cannot modify a rectangle passed to the function by reference, I figured I should either return a collision rectangle or `null` if there is no collision. Probably not the best solution (not sure), but alright.

Thanks for pointing that out!

**Comment by mantognini** [comment]
Sounds good to me from a Java perspective. ;-)
