### ISSUE TITLE
Unable to set RenderWindow size

### ISSUE THREAD

**Issue by kinglime** [pdinklag/JSFML#67]
The following code does not work on my machine:
```java
final RenderWindow window = new RenderWindow(new VideoMode(1280, 720));
window.setSize(new Vector2i(800, 600));
```

The window moves but does not change size.

**Comment by kinglime** [comment]
Just noticed this was fixed in 6bd9e6558b64017c8cf63b0aecc411e5702aab5e I'll see myself out...

**Comment by kinglime** [comment]
@pdinklag I hate to bug you but do you think you could either write a short tutorial on how to compile JSFML from source or release a new .jar because I really need to fix this for my game.

**Comment by pdinklag** [comment]
Please let me know if any info was lacking from the building info page (https://github.com/pdinklag/JSFML/wiki/Building-JSFML).

Sorry I'm so inactive with this, I no longer have any needs for JSFML privately, so there's a bit of a lack of motivation to continue. I shall address this soon.

**Comment by kinglime** [comment]
@pdinklag Once I found that page I figure everything out!
