### ISSUE TITLE
Hello, I understand this is no longer under development

### ISSUE THREAD

**Issue by KalebArnold** [pdinklag/JSFML#70]
I understand this is not longer under development but, I was wondering if you may be able to help with this issue I'm having.
I don't have this issue on my pc but I do on my laptop. I've tried copying across the .JSFML file from the user dir. And also just rebooting.

Thank you!

![image](https://user-images.githubusercontent.com/25988731/37770719-3eb339e0-2dcd-11e8-96eb-0fd13a1971c7.png)

**Comment by pdinklag** [comment]
Looks like a DLL is missing.

Do you have the _Visual C++ Redistributable for Visual Studio 2013_ installed on your laptop? It's probably that one, but sadly, Java doesn't mention which dependent library is missing.

If it's not that one, you can try and find out by opening `sfml-system-2.dll` in the [Dependency Walker](http://www.dependencywalker.com/), that will list all dependencies of the DLL and shall also indicate what's missing exactly.

**Comment by KalebArnold** [comment]
That's the issue thank you very much!

**Comment by rbeesley** [comment]
I found that _Visual C++ Redistributable for Visual Studio 2010_ was needed. 🤔

Regardless, this is an error which is not especially clear on how to resolve and should probably be documented somewhere other than the list of Issues.
