### ISSUE TITLE
Window shows, but the scene doesn't render

### ISSUE THREAD

**Issue by rbeesley** [pdinklag/JSFML#71]
@pdinklag, this is more for me to document this issue, but if you have any suggestions for how to debug this, I'd be open to them.

On one machine I have, I was able to run the jsfml-test.jar (`java -jar .\jsfml-test.jar`) and verify that this library was going to meet my needs. I set up a second machine where I might do some development and configured everything the same way, but this time when I ran the jsfml-test.jar, I saw a window, but the scene didn't render. The window was black and blank. The window does respond to pressing the ESC key to close, so the main loop seems to be processing.

I thought maybe this was related to #69. I don't get a (Not Responding) window in that I verified that the loop was processing, but it's possible that the blank window was what they meant when writing (Not Responding).

Working setup: Windows 10, 64-bit, HDPI, Integrated Intel Graphics, Java 11
Not working setup: Windows 10, 64-bit, mixed mode dual monitor w/ one monitor HDPI, nVidia Quadro K420, Java 11

I don't know that this is DPI or multimonitor related, but those are perhaps the most significant differences between the two machines. There are different graphical chipsets, but both report Shader.isAvailable(): true, so presumably the cards are detected and initialized correct. The console doesn't indicate any errors.

**Comment by rbeesley** [comment]
This is an upstream issue with SFML. I found another project which uses SFML C++ library and it exhibits the same behavior.

**Comment by rbeesley** [comment]
And it is outside SFML. Other graphics tests and benchmarks failed too. Furthermore, reboot fixed the problem. Not sure what the root cause was, but my guess now is that it was driver level or higher.

**Comment by pdinklag** [comment]
Glad to see it's "magically" fixed.

The only hint I could have given is try it with the original SFML of the same version JSFML uses to see if this issue is specific to the Java binding or not, which would have been strange.

The big issue is that the actual SFML is probably far further now and bugs have been fixed -- fixes that are not reflected in JSFML. I can only hope someone is willing to pick it up again at some point.

Thanks for documenting this!
